baseURL = "https://blue-coast-01c25121e.azurestaticapps.net/"
languageCode = "en-us"
title = "Create:Frontend"
theme = "beautifulhugo"
summaryLength = 7000
DefaultContentLanguage = "en"
[languages]
  [languages.en]
    weight = 1 
    contentDir = "content/en" # English
  [languages.de]
    weight = 2
    contentDir = "content/de" # German
